version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=orderservice_db'
      - 'POSTGRES_PASSWORD=orderservice_pwd'
      - 'POSTGRES_USER=orderservice'
    ports:
      - '5432:5432'
    restart: 'always'
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U orderservice -d orderservice_db'" ]

  orderservice-inner:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - 'DB_URL=jdbc:postgresql://postgres/orderservice_db'
      - 'DB_USERNAME=orderservice'
      - 'DB_PASSWORD=orderservice_pwd'
      - 'ORDER_NUMBER_API_URL=http://localhost:8081/api/v1/numbers'
    depends_on:
      postgres:
        condition: service_healthy
