server:
  port: ${SERVER_PORT:8080}
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/orderservice_db}
    username: ${DB_USERNAME:orderservice_admin}
    password: ${DB_PASSWORD:orderservice_password}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
order:
  number:
    api:
      url: http://127.0.0.1:8081/api/v1/numbers
management:
  endpoints:
    enabled-by-default: false
    web.exposure.include: health, prometheus, loggers
  endpoint:
    health.enabled: true
    prometheus.enabled: true
    loggers.enabled: true