spring:
  application:
    name: orderservice
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/orderservice_db}
    username: ${DB_USERNAME:orderservice}
    password: ${DB_PASSWORD:orderservice_pwd}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
management:
  endpoints:
    enabled-by-default: false
    web.exposure.include: health, prometheus, loggers
  endpoint:
    health.enabled: true
    prometheus.enabled: true
    loggers.enabled: true
order:
  number:
    api:
      url: http://localhost:8081/api/v1/numbers
logging:
  level:
    root: debug